version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  flask-redirect:
    image: "alexvarney/httpredirect:latest"
    environment:
      - VIRTUAL_HOST=redirect.dev.varney.me
      - PORT=80
    ports:
      - "8080:80"
  
  redis:
    image: "redis:alpine"
